package org.milaifontanals.clubEsportiu.vista;


import java.awt.Font;
import java.awt.font.TextAttribute;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.milaifontanals.clubEsportiu.model.Categoria;
import org.milaifontanals.clubEsportiu.model.Equip;
import org.milaifontanals.clubEsportiu.model.ExceptionClub;
import org.milaifontanals.clubEsportiu.model.Jugador;
import org.milaifontanals.clubEsportiu.model.Temporada;
import org.milaifontanals.clubEsportiu.persistencia.GestorBDClubEsportiuException;
import org.milaifontanals.clubEsportiu.persistencia.IGestorBDClubEsportiu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author isard
 */
public class InserirEquip extends javax.swing.JFrame {

    private IGestorBDClubEsportiu capaOracleJDBC = null;
    private Temporada temp;
    private List<Categoria> llCategories;
    private List<Temporada> lltemporades;
    private Character tipus;
    private GestioEquips fGestio;
    public InserirEquip( IGestorBDClubEsportiu capa, Temporada temp, GestioEquips f) throws GestorBDClubEsportiuException {
        initComponents();
        this.capaOracleJDBC = capa;
        this.temp = temp;
        this.fGestio=f;
        llCategories = capaOracleJDBC.obtenirCategories("");
//        comboCategoria.addItem(new Categoria());
        for (Iterator<Categoria> iterator = llCategories.iterator(); iterator.hasNext();) {
            Categoria next = iterator.next();
            comboCategoria.addItem(next);

        }
        lltemporades = capaOracleJDBC.obtenirTemporades();
        for (Iterator<Temporada> iterator = lltemporades.iterator(); iterator.hasNext();) {
            Temporada next = iterator.next();
            comboTemporada.addItem(next);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        rbFemeni = new javax.swing.JRadioButton();
        rbMasculi = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        tornarEnrere = new javax.swing.JLabel();
        comboTemporada = new javax.swing.JComboBox<>();
        comboCategoria = new javax.swing.JComboBox<>();
        rbMix = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Introduir/Modificar Jugador");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Introdueix les dades del equip");

        jLabel2.setText("Nom: ");

        jLabel4.setText("Temporada:");

        jLabel5.setText("Categoria:");

        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbFemeni);
        rbFemeni.setText("Femieni");
        rbFemeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemeniActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbMasculi);
        rbMasculi.setText("Masculi");

        jLabel8.setText("Sexe");

        btnInserir.setText("Inserir/Modificar");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        tornarEnrere.setForeground(new java.awt.Color(0, 153, 255));
        tornarEnrere.setText("Tornar Enrere");
        tornarEnrere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Font font = tornarEnrere.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        tornarEnrere.setFont(font.deriveFont(attributes));
        tornarEnrere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tornarEnrereMouseClicked(evt);
            }
        });

        comboTemporada.setMaximumRowCount(6);
        comboTemporada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTemporadaActionPerformed(evt);
            }
        });

        comboCategoria.setMaximumRowCount(6);
        comboCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbMix);
        rbMix.setText("Mix");
        rbMix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(comboTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(rbFemeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbMasculi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbMix))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tornarEnrere)
                                .addGap(88, 88, 88)
                                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFemeni)
                    .addComponent(jLabel8)
                    .addComponent(rbMasculi)
                    .addComponent(rbMix))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInserir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tornarEnrere, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
     String nomEquip = txtNom.getText().trim();
    Categoria categoriaSeleccionada = (Categoria) comboCategoria.getSelectedItem();
    Temporada temporadaSeleccionada=(Temporada) comboTemporada.getSelectedItem();
    char tipus = 0; 
    int categoriaId = 0; 
    Equip e = null; 

   
    if (nomEquip.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El nom de l'equip és obligatori.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    
    if (categoriaSeleccionada == null) {
        JOptionPane.showMessageDialog(this, "Cal seleccionar una categoria.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    } else {
        categoriaId = categoriaSeleccionada.getId(); 
    }

    if (rbFemeni.isSelected()) {
        tipus = 'D'; 
    } else if (rbMasculi.isSelected()) {
        tipus = 'H'; 
    } else if (rbMix.isSelected()) {
        tipus = 'M'; 
    } else {
        JOptionPane.showMessageDialog(this, "Cal seleccionar un tipus de sexe per a l'equip.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        e = capaOracleJDBC.obtenirEquipPerTemporada(nomEquip, temp);
    } catch (GestorBDClubEsportiuException ex) {
        Logger.getLogger(InserirEquip.class.getName()).log(Level.SEVERE, null, ex);
    }

    if (e != null) {
        JOptionPane.showMessageDialog(this, "Ja existeix un equip amb aquest nom per a la temporada seleccionada.", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    e = new Equip();
    e.setNom(nomEquip);
    e.setIdCategoria(categoriaId);
    
    try {
        e.setIdAny(temporadaSeleccionada.getAny_temp());
        e.setTipus(tipus); 
    } catch (ExceptionClub ex) {
        Logger.getLogger(InserirEquip.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error en configurar el tipus d'equip: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

   
    try {
        capaOracleJDBC.afegirEquip(e); 
        capaOracleJDBC.confirmarCanvis();
        JOptionPane.showMessageDialog(this, "Equip afegit correctament!", "Èxit", JOptionPane.INFORMATION_MESSAGE);
        fGestio.setVisible(true);
        fGestio.cercarEquips();
        this.dispose();
    } catch (GestorBDClubEsportiuException ex) {
        Logger.getLogger(InserirEquip.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error al afegir l'equip: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void rbFemeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemeniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemeniActionPerformed

    private void tornarEnrereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tornarEnrereMouseClicked
        fGestio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tornarEnrereMouseClicked

    private void comboTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTemporadaActionPerformed

    }//GEN-LAST:event_comboTemporadaActionPerformed

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed

    }//GEN-LAST:event_comboCategoriaActionPerformed

    private void rbMixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMixActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InserirModificarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InserirModificarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InserirModificarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InserirModificarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InserirModificarJugador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<Categoria > comboCategoria;
    private javax.swing.JComboBox<Temporada > comboTemporada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rbFemeni;
    private javax.swing.JRadioButton rbMasculi;
    private javax.swing.JRadioButton rbMix;
    private javax.swing.JLabel tornarEnrere;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
