package org.milaifontanals.clubEsportiu.vista;

import java.awt.Font;
import java.awt.Image;
import java.awt.font.TextAttribute;
import java.io.File;
import java.time.ZoneId;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.milaifontanals.clubEsportiu.model.Jugador;
import org.milaifontanals.clubEsportiu.model.Temporada;
import org.milaifontanals.clubEsportiu.persistencia.GestorBDClubEsportiuException;
import org.milaifontanals.clubEsportiu.persistencia.IGestorBDClubEsportiu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author isard
 */
public class InserirModificarJugador extends javax.swing.JFrame {

    private IGestorBDClubEsportiu capaOracleJDBC = null;
    private int jugadorId;
    private Jugador jugador;
    private Jugador jugadorOriginal;
    private Temporada temp;
    private GestioJugadors fJugador;
    private String rutaFotoSeleccionada = null;

    /**
     * Creates new form IntroduirModificarJugador
     *
     * @param jugadorId
     * @param jugador
     * @param temp
     * @param f
     * @param capa
     */
    public InserirModificarJugador(int jugadorId, IGestorBDClubEsportiu capa, Temporada temp, GestioJugadors f) {
        initComponents();
        this.jugadorId = jugadorId;
        this.capaOracleJDBC = capa;
        this.temp = temp;
        this.fJugador = f;
        if (this.jugadorId != 0) {
            mostrarJugador();
        } else {
            jugador = new Jugador();
        }
    }

    public void mostrarJugador() {
        try {
            jugador = capaOracleJDBC.filtrarJugadorPerId(jugadorId);

            txtNom.setText(jugador.getNom());
            txtCognom.setText(jugador.getCognoms());
            txtFiRevisio.setText(jugador.getRevisio());
            txtIdLegal.setText(jugador.getIdLegal());
            txtIban.setText(jugador.getIBAN());
            txtAdreca.setText(jugador.getAdreca());
            txtCodiPostal.setText(jugador.getCodiPostal());
            txtPoblacio.setText(jugador.getPoblacio());
            Date date = Date.from(jugador.getDataNaixement().atStartOfDay(ZoneId.systemDefault()).toInstant());
            txtNaix.setDate(date);
            afegirImgAlLabel(jugador.getFoto());
//            txtNaixement.setText(jugador.getDataNaixement().toString());

            rbHome.setSelected(jugador.getSexe() == 'H');
            rbDona.setSelected(jugador.getSexe() != 'H');
        } catch (GestorBDClubEsportiuException ex) {
            Logger.getLogger(InserirModificarJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtCognom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFiRevisio = new javax.swing.JTextField();
        txtIdLegal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIban = new javax.swing.JTextField();
        txtAdreca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btFoto = new javax.swing.JButton();
        txtCodiPostal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPoblacio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNaix = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbHome = new javax.swing.JRadioButton();
        rbDona = new javax.swing.JRadioButton();
        tornarEnrere = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnInserir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Introduir/Modificar Jugador");
        setPreferredSize(new java.awt.Dimension(820, 480));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Nom: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 20));

        txtNom.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNom.setForeground(new java.awt.Color(0, 102, 102));
        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });
        jPanel1.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 276, -1));

        txtCognom.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCognom.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(txtCognom, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 276, -1));

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Cognom:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 30));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Revisió(SI/NO):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 20));

        txtFiRevisio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtFiRevisio.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(txtFiRevisio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 276, -1));

        txtIdLegal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdLegal.setForeground(new java.awt.Color(0, 102, 102));
        txtIdLegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLegalActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdLegal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 276, -1));

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Id Legal");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 20));

        txtIban.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIban.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(txtIban, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 276, -1));

        txtAdreca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtAdreca.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(txtAdreca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 276, -1));

        jLabel7.setBackground(new java.awt.Color(0, 102, 102));
        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("IBAN:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 50, 20));

        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Adreça:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 50, 20));

        btFoto.setBackground(new java.awt.Color(0, 102, 102));
        btFoto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btFoto.setForeground(new java.awt.Color(255, 255, 255));
        btFoto.setText("Upload Foto");
        btFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFotoActionPerformed(evt);
            }
        });
        jPanel1.add(btFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 169, -1));

        txtCodiPostal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCodiPostal.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(txtCodiPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 276, -1));

        jLabel10.setBackground(new java.awt.Color(0, 102, 102));
        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Codi Postal:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 79, 20));

        txtPoblacio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPoblacio.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(txtPoblacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 276, -1));

        jLabel11.setBackground(new java.awt.Color(0, 102, 102));
        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Població:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));
        jPanel1.add(txtNaix, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 276, -1));

        jLabel9.setBackground(new java.awt.Color(0, 102, 102));
        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Data Naixement:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 99, -1));
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 180, 120));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Sexe:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 37, 20));

        buttonGroup1.add(rbHome);
        rbHome.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rbHome.setForeground(new java.awt.Color(0, 102, 102));
        rbHome.setText("Home");
        rbHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHomeActionPerformed(evt);
            }
        });
        jPanel1.add(rbHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));

        buttonGroup1.add(rbDona);
        rbDona.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rbDona.setForeground(new java.awt.Color(0, 102, 102));
        rbDona.setText("Dona");
        jPanel1.add(rbDona, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, -1, -1));

        tornarEnrere.setBackground(new java.awt.Color(0, 102, 102));
        tornarEnrere.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tornarEnrere.setForeground(new java.awt.Color(0, 102, 102));
        tornarEnrere.setText("Tornar Enrere");
        tornarEnrere.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 102, 102), null, new java.awt.Color(0, 102, 102)));
        tornarEnrere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Font font = tornarEnrere.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        tornarEnrere.setFont(font.deriveFont(attributes));
        tornarEnrere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tornarEnrereMouseClicked(evt);
            }
        });
        jPanel1.add(tornarEnrere, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, 25));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 3, true));

        btnInserir.setBackground(new java.awt.Color(0, 102, 102));
        btnInserir.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnInserir.setForeground(new java.awt.Color(255, 255, 255));
        btnInserir.setText("Inserir/Modificar");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(btnInserir)
                .addGap(17, 17, 17))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Introdueix/Modifica les dades del jugador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 268, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 770, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed

//        Jugador j = new Jugador();
        if (jugadorId != 0) {
            jugadorOriginal = jugador.clone();
        }
        String nom = txtNom.getText().trim();
        String cognom = txtCognom.getText().trim();
        String Revisio = txtFiRevisio.getText().trim();
        String idLegal = txtIdLegal.getText().trim();
        String iban = txtIban.getText().trim();
        String adreca = txtAdreca.getText().trim();
        String codiPostal = txtCodiPostal.getText().trim();
        String poblacio = txtPoblacio.getText().trim();
        java.util.Date date = txtNaix.getDate();

        if (nom.isEmpty() || cognom.isEmpty() || Revisio.isEmpty() || idLegal.isEmpty() || iban.isEmpty() || adreca.isEmpty() || date == null
                || (rbDona.isSelected() == false && rbHome.isSelected() == false) || lblFoto.getIcon() == null || codiPostal.isEmpty() || poblacio.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tots els camps són obligatoris. Si us plau, ompliu-los tots.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

//        select * from membre m join equip e on m.id_equip in (select id from equip where tipus='M') and m.id_jugador in (select
//id from jugador where m.id_jugador=id);
        try {

            jugador.setNom(nom);
            jugador.setCognoms(cognom);
            jugador.setSexe(rbHome.isSelected() ? 'H' : 'D');
            jugador.setIBAN(iban);
            jugador.setRevisio(Revisio);
            jugador.setAdreca(adreca);
            jugador.setCodiPostal(codiPostal);
            jugador.setPoblacio(poblacio);
            jugador.setIdLegal(idLegal);
            jugador.setDataNaixement(date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            System.out.println(rutaFotoSeleccionada);
            jugador.setFoto(rutaFotoSeleccionada != null ? rutaFotoSeleccionada : jugador.getFoto());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en les dades del jugador: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//            ex.printStackTrace();
            return;
        }
        //Per inserir
        if (jugadorId == 0) {
            try {
                if (capaOracleJDBC.validarIdLegalExistent(jugador)) {
                    JOptionPane.showMessageDialog(null, "El id_legal ja existeix a la base de dades. Si us plau, utilitzi un altre id_legal.",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                capaOracleJDBC.afegirJugador(jugador);

                JOptionPane.showMessageDialog(null, "Jugador inserit correctament");
                capaOracleJDBC.confirmarCanvis();
            } catch (GestorBDClubEsportiuException ex) {
                JOptionPane.showMessageDialog(null, "Error al insertar el jugador: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

            }
            //Per modficiar
        } else {
            try {

                boolean canviIdLegal = !jugadorOriginal.getIdLegal().equals(jugador.getIdLegal());

                if (canviIdLegal && capaOracleJDBC.validarIdLegalExistent(jugador)) {
                    JOptionPane.showMessageDialog(null, "El id_legal ja existeix a la base de dades. Si us plau, utilitzi un altre id_legal.",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                boolean canviSexe = jugadorOriginal.getSexe() != jugador.getSexe();
                boolean canviNaixement = !jugadorOriginal.getDataNaixement().equals(jugador.getDataNaixement());
                boolean senseEquip = capaOracleJDBC.jugadorSenseEquip(jugador);
                boolean equipMix = capaOracleJDBC.jugadorEquipMix(jugador);
                boolean validaCanviNaix = capaOracleJDBC.validaCanviNaixement(jugadorOriginal, jugador.getDataNaixement(), temp.getAny_temp());

                if (canviSexe && !(senseEquip || equipMix)) {
                    JOptionPane.showMessageDialog(null, "No es pot modificar el sexe perquè el jugador està en equips no mixtos.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (canviNaixement && !(senseEquip || validaCanviNaix)) {
                    JOptionPane.showMessageDialog(null, "No es pot modificar la data de naixement perquè afecta la categoria del jugador.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                capaOracleJDBC.modificarJugador(jugador);
                capaOracleJDBC.confirmarCanvis();
                JOptionPane.showMessageDialog(null, "Jugador modificat correctament.");

            } catch (GestorBDClubEsportiuException ex) {
                JOptionPane.showMessageDialog(null, "Error al modificar el jugador: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                
            }
        }


    }//GEN-LAST:event_btnInserirActionPerformed

    private void rbHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbHomeActionPerformed

    private void tornarEnrereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tornarEnrereMouseClicked
//        GestioJugadors log = new GestioJugadors(capaOracleJDBC, temp, fLogin);
        fJugador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tornarEnrereMouseClicked

    private void txtIdLegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLegalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdLegalActionPerformed

    private void btFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFotoActionPerformed

        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Busca la foto del jugador");
        fc.setCurrentDirectory(new File("C:\\Users\\isard\\Desktop\\FOTOS-bd"));

        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fc.getSelectedFile();
            rutaFotoSeleccionada = selectedFile.getAbsolutePath();

            afegirImgAlLabel(rutaFotoSeleccionada);

        }

    }//GEN-LAST:event_btFotoActionPerformed
    private void afegirImgAlLabel(String ruta) {

        ImageIcon iconoOriginal = new ImageIcon(ruta);
        Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                lblFoto.getWidth(),
                lblFoto.getHeight(),
                Image.SCALE_SMOOTH
        );
        lblFoto.setIcon(new ImageIcon(imagenEscalada));
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InserirModificarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InserirModificarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InserirModificarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InserirModificarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InserirModificarJugador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFoto;
    private javax.swing.JButton btnInserir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JRadioButton rbDona;
    private javax.swing.JRadioButton rbHome;
    private javax.swing.JLabel tornarEnrere;
    private javax.swing.JTextField txtAdreca;
    private javax.swing.JTextField txtCodiPostal;
    private javax.swing.JTextField txtCognom;
    private javax.swing.JTextField txtFiRevisio;
    private javax.swing.JTextField txtIban;
    private javax.swing.JTextField txtIdLegal;
    private com.toedter.calendar.JDateChooser txtNaix;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPoblacio;
    // End of variables declaration//GEN-END:variables
}
