package org.milaifontanals.clubEsportiu.vista;

import java.awt.Font;
import java.awt.Image;
import java.awt.font.TextAttribute;
import java.awt.image.BufferedImage;
import java.io.File;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.milaifontanals.clubEsportiu.model.ExceptionClub;
import org.milaifontanals.clubEsportiu.model.Jugador;
import org.milaifontanals.clubEsportiu.model.Temporada;
import org.milaifontanals.clubEsportiu.persistencia.GestorBDClubEsportiuException;
import org.milaifontanals.clubEsportiu.persistencia.IGestorBDClubEsportiu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author isard
 */
public class InserirModificarJugador extends javax.swing.JFrame {

    private IGestorBDClubEsportiu capaOracleJDBC = null;
    private int jugadorId;
    private Jugador jugador;
    private Jugador jugadorOriginal;
    private Temporada temp;
    private GestioJugadors fJugador;
    private String rutaFotoSeleccionada;

    /**
     * Creates new form IntroduirModificarJugador
     *
     * @param jugadorId
     * @param jugador
     * @param temp
     * @param f
     * @param capa
     */
    public InserirModificarJugador(int jugadorId, IGestorBDClubEsportiu capa, Temporada temp, GestioJugadors f) {
        initComponents();
        this.jugadorId = jugadorId;
        this.capaOracleJDBC = capa;
        this.temp = temp;
        this.fJugador = f;
        if (this.jugadorId != 0) {
            mostrarJugador();
        } else {
            jugador = new Jugador();
        }
    }

    public void mostrarJugador() {
        try {
            jugador = capaOracleJDBC.filtrarJugadorPerId(jugadorId);

            txtNom.setText(jugador.getNom());
            txtCognom.setText(jugador.getCognoms());
            txtFiRevisio.setText(jugador.getRevisio());
            txtIdLegal.setText(jugador.getIdLegal());
            txtIban.setText(jugador.getIBAN());
            txtAdreca.setText(jugador.getAdreca());
            txtCodiPostal.setText(jugador.getCodiPostal());
            txtPoblacio.setText(jugador.getPoblacio());
            Date date = Date.from(jugador.getDataNaixement().atStartOfDay(ZoneId.systemDefault()).toInstant());
            txtNaix.setDate(date);
            afegirImgAlLabel(jugador.getFoto());
//            txtNaixement.setText(jugador.getDataNaixement().toString());

            rbHome.setSelected(jugador.getSexe() == 'H');
            rbDona.setSelected(jugador.getSexe() != 'H');
        } catch (GestorBDClubEsportiuException ex) {
            Logger.getLogger(InserirModificarJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtCognom = new javax.swing.JTextField();
        txtIdLegal = new javax.swing.JTextField();
        txtFiRevisio = new javax.swing.JTextField();
        txtIban = new javax.swing.JTextField();
        txtAdreca = new javax.swing.JTextField();
        rbHome = new javax.swing.JRadioButton();
        rbDona = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        txtNaix = new com.toedter.calendar.JDateChooser();
        tornarEnrere = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        btFoto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtCodiPostal = new javax.swing.JTextField();
        txtPoblacio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Introduir/Modificar Jugador");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Introdueix/Modifica les dades del jugador");

        jLabel2.setText("Nom: ");

        jLabel3.setText("Cognom:");

        jLabel4.setText("Revisió:");

        jLabel5.setText("Id Legal");

        jLabel6.setText("Adreça:");

        jLabel7.setText("IBAN");

        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });

        txtIdLegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLegalActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbHome);
        rbHome.setText("Home");
        rbHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHomeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbDona);
        rbDona.setText("Dona");

        jLabel8.setText("Sexe");

        jLabel9.setText("Data Naixement:");

        btnInserir.setText("Inserir/Modificar");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        tornarEnrere.setForeground(new java.awt.Color(0, 153, 255));
        tornarEnrere.setText("Tornar Enrere");
        tornarEnrere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Font font = tornarEnrere.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        tornarEnrere.setFont(font.deriveFont(attributes));
        tornarEnrere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tornarEnrereMouseClicked(evt);
            }
        });

        btFoto.setText("Upload Foto");
        btFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFotoActionPerformed(evt);
            }
        });

        jLabel10.setText("Codi Postal:");

        jLabel11.setText("Població:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(tornarEnrere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInserir)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPoblacio)
                    .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(txtCognom)
                    .addComponent(txtFiRevisio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdLegal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIban)
                    .addComponent(txtAdreca)
                    .addComponent(txtNaix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodiPostal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDona))
                    .addComponent(btFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbHome)
                            .addComponent(jLabel8)
                            .addComponent(rbDona))
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCognom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFiRevisio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtIban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtAdreca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodiPostal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPoblacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtNaix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInserir)
                    .addComponent(tornarEnrere, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed

//        Jugador j = new Jugador();
        jugadorOriginal = jugador.clone();
        String nom = txtNom.getText().trim();
        String cognom = txtCognom.getText().trim();
        String Revisio = txtFiRevisio.getText().trim();
        String idLegal = txtIdLegal.getText().trim();
        String iban = txtIban.getText().trim();
        String adreca = txtAdreca.getText().trim();
        String codiPostal = txtCodiPostal.getText().trim();
        String poblacio = txtPoblacio.getText().trim();
        java.util.Date date = txtNaix.getDate();
        

        if (nom.isEmpty() || cognom.isEmpty() || Revisio.isEmpty() || idLegal.isEmpty() || iban.isEmpty() || adreca.isEmpty() || date == null
                || (rbDona.isSelected() == false && rbHome.isSelected() == false) || lblFoto.getIcon() == null || codiPostal.isEmpty() || poblacio.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tots els camps són obligatoris. Si us plau, ompliu-los tots.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

//        select * from membre m join equip e on m.id_equip in (select id from equip where tipus='M') and m.id_jugador in (select
//id from jugador where m.id_jugador=id);
        try {

            jugador.setNom(nom);
            jugador.setCognoms(cognom);
            jugador.setSexe(rbHome.isSelected() ? 'H' : 'D');
            jugador.setIBAN(iban);
            jugador.setRevisio(Revisio);
            jugador.setAdreca(adreca);
            jugador.setCodiPostal(codiPostal);
            jugador.setPoblacio(poblacio);
            jugador.setIdLegal(idLegal);
            jugador.setDataNaixement(date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            System.out.println(rutaFotoSeleccionada);
            jugador.setFoto(rutaFotoSeleccionada!=null?rutaFotoSeleccionada:jugador.getFoto());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en les dades del jugador: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//            ex.printStackTrace();
            return;
        }
        //Per inserir
        if (jugadorId == 0) {
            try {
                capaOracleJDBC.afegirJugador(jugador);

//                capaOracleJDBC.confirmarCanvis();
                JOptionPane.showMessageDialog(null, "Jugador inserit correctament");
            } catch (GestorBDClubEsportiuException ex) {
                JOptionPane.showMessageDialog(null, "Error al insertar el jugador: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
            //Per modficiar
        } else {
            try {
                // Modificar jugador
                boolean canviSexe = jugadorOriginal.getSexe() != jugador.getSexe();
                boolean canviNaixement = !jugadorOriginal.getDataNaixement().equals(jugador.getDataNaixement());
                boolean senseEquip = capaOracleJDBC.jugadorSenseEquip(jugador);
                boolean equipMix = capaOracleJDBC.jugadorEquipMix(jugador);
                boolean validaCanviNaix = capaOracleJDBC.validaCanviNaixement(jugadorOriginal, jugador.getDataNaixement(), temp.getAny_temp());

                if (canviSexe && !(senseEquip || equipMix)) {
                    JOptionPane.showMessageDialog(null, "No es pot modificar el sexe perquè el jugador està en equips no mixtos.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (canviNaixement && !(senseEquip || validaCanviNaix)) {
                    JOptionPane.showMessageDialog(null, "No es pot modificar la data de naixement perquè afecta la categoria del jugador.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                capaOracleJDBC.modificarJugador(jugador);
                capaOracleJDBC.confirmarCanvis();
                JOptionPane.showMessageDialog(null, "Jugador modificat correctament.");

            } catch (GestorBDClubEsportiuException ex) {
                JOptionPane.showMessageDialog(null, "Error al modificar el jugador: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }


    }//GEN-LAST:event_btnInserirActionPerformed

    private void rbHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbHomeActionPerformed

    private void tornarEnrereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tornarEnrereMouseClicked
//        GestioJugadors log = new GestioJugadors(capaOracleJDBC, temp, fLogin);
        fJugador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tornarEnrereMouseClicked

    private void txtIdLegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLegalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdLegalActionPerformed

    private void btFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFotoActionPerformed

        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Busca la foto del jugador");
        fc.setCurrentDirectory(new File("C:\\Users\\isard\\Desktop\\FOTOS-bd"));

        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fc.getSelectedFile();
            rutaFotoSeleccionada = selectedFile.getAbsolutePath(); 
            
            afegirImgAlLabel(rutaFotoSeleccionada);

        }

    }//GEN-LAST:event_btFotoActionPerformed
    private void afegirImgAlLabel(String ruta){
        
  
            ImageIcon iconoOriginal = new ImageIcon(ruta);
            Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                    lblFoto.getWidth(),
                    lblFoto.getHeight(),
                    Image.SCALE_SMOOTH
            );
            lblFoto.setIcon(new ImageIcon(imagenEscalada)); 
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InserirModificarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InserirModificarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InserirModificarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InserirModificarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InserirModificarJugador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFoto;
    private javax.swing.JButton btnInserir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JRadioButton rbDona;
    private javax.swing.JRadioButton rbHome;
    private javax.swing.JLabel tornarEnrere;
    private javax.swing.JTextField txtAdreca;
    private javax.swing.JTextField txtCodiPostal;
    private javax.swing.JTextField txtCognom;
    private javax.swing.JTextField txtFiRevisio;
    private javax.swing.JTextField txtIban;
    private javax.swing.JTextField txtIdLegal;
    private com.toedter.calendar.JDateChooser txtNaix;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPoblacio;
    // End of variables declaration//GEN-END:variables
}
