package org.milaifontanals.clubEsportiu.vista;



import com.formdev.flatlaf.FlatLightLaf;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import org.milaifontanals.clubEsportiu.model.Usuari;
import org.milaifontanals.clubEsportiu.persistencia.GestorBDClubEsportiuException;
import org.milaifontanals.clubEsportiu.persistencia.IGestorBDClubEsportiu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author isard
 */
public class Login extends javax.swing.JFrame {

    private IGestorBDClubEsportiu capaOracleJDBC = null;
    static private String nomClassePersistencia = null;

    /**
     * Creates new form Login
     */
    public Login() {
        
        try {
            // Disseny de la interfície
            this.capaOracleJDBC = (IGestorBDClubEsportiu) Class.forName(nomClassePersistencia).newInstance();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
         

        System.out.println("Connexio establerta");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblInici = new javax.swing.JLabel();
        lblUsuari = new javax.swing.JLabel();
        lblConstrasenya = new javax.swing.JLabel();
        txtUsuari = new javax.swing.JTextField();
        txtContrasenya = new javax.swing.JTextField();
        btneEnviar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblInici1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICI DE SESSIÓ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(802, 420));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblInici.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblInici.setForeground(new java.awt.Color(0, 102, 102));
        lblInici.setText("INICI DE SESSIÓ");

        lblUsuari.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblUsuari.setForeground(new java.awt.Color(0, 102, 102));
        lblUsuari.setText("Usuari:");

        lblConstrasenya.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblConstrasenya.setForeground(new java.awt.Color(0, 102, 102));
        lblConstrasenya.setText("Constrasenya:");

        txtUsuari.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        txtUsuari.setForeground(new java.awt.Color(0, 102, 102));

        txtContrasenya.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        txtContrasenya.setForeground(new java.awt.Color(0, 102, 102));
        txtContrasenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenyaActionPerformed(evt);
            }
        });

        btneEnviar.setBackground(new java.awt.Color(0, 102, 102));
        btneEnviar.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        btneEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btneEnviar.setText("Enviar");
        btneEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblInici))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblConstrasenya)
                            .addComponent(lblUsuari))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btneEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsuari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtContrasenya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblInici)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuari)
                    .addComponent(txtUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConstrasenya)
                    .addComponent(txtContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btneEnviar)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setToolTipText("");

        lblLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\isard\\Desktop\\FOTOS-bd\\7517242-Red.jpg")); // NOI18N
        lblLogo.setMaximumSize(new java.awt.Dimension(2000, 2000));

        lblInici1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblInici1.setForeground(new java.awt.Color(255, 255, 255));
        lblInici1.setText("CLUB ESPORTIU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblInici1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblInici1)
                .addGap(18, 18, 18)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtContrasenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenyaActionPerformed

    private void btneEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneEnviarActionPerformed
         Usuari usu = null;
    
    if (txtUsuari.getText().isEmpty() || txtContrasenya.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Error. El nom o la contrasenya estan buits", "Error", JOptionPane.ERROR_MESSAGE);
    return;
    } else {
             try {
                 usu = capaOracleJDBC.obtenirUsuari(txtUsuari.getText().trim(), txtContrasenya.getText().trim());
             } catch (GestorBDClubEsportiuException ex) {
                 Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
             }
        if (usu == null) {
            JOptionPane.showMessageDialog(this, "Error. El nom o la contrasenya son incorrectes", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            FinestraLogin finestraLogin = new FinestraLogin(usu,capaOracleJDBC);
            finestraLogin.setVisible(true); 
            this.dispose(); 
        }
    }

    }//GEN-LAST:event_btneEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
try {
    javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
} catch (UnsupportedLookAndFeelException ex) {
    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex); // Incluye 'ex' para registrar el error
}
 

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (args.length == 0) {
                    System.out.println("Cal passar el nom de la classe que dona la persistència com a primer argument");
                    System.exit(0);
                }
                nomClassePersistencia = args[0];
                new Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneEnviar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblConstrasenya;
    private javax.swing.JLabel lblInici;
    private javax.swing.JLabel lblInici1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsuari;
    private javax.swing.JTextField txtContrasenya;
    private javax.swing.JTextField txtUsuari;
    // End of variables declaration//GEN-END:variables
}
