package org.milaifontanals.clubEsportiu.vista;


import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.milaifontanals.clubEsportiu.model.Usuari;
import org.milaifontanals.clubEsportiu.persistencia.GestorBDClubEsportiuException;
import org.milaifontanals.clubEsportiu.persistencia.IGestorBDClubEsportiu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author isard
 */
public class Login extends javax.swing.JFrame {

    private IGestorBDClubEsportiu capaOracleJDBC = null;
//    private GestorBDClubEsportiuJdbc capaOracleJDBCDos = null;
    static private String nomClassePersistencia = null;

    /**
     * Creates new form Login
     */
    public Login() {
        try {
            // Disseny de la interfície
            this.capaOracleJDBC = (IGestorBDClubEsportiu) Class.forName(nomClassePersistencia).newInstance();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(LoginUsuari.class.getName()).log(Level.SEVERE, null, ex);
        }
        //            this.capaOracleJDBCDos = new GestorBDClubEsportiuJdbc();
        System.out.println("Connexio establerta");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInici = new javax.swing.JLabel();
        lblUsuari = new javax.swing.JLabel();
        lblConstrasenya = new javax.swing.JLabel();
        txtUsuari = new javax.swing.JTextField();
        txtContrasenya = new javax.swing.JTextField();
        btneEnviar = new javax.swing.JButton();
        lblRecuperaCOntrasenya = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblInici1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICI DE SESSIÓ");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblInici.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInici.setText("INICI DE SESSIÓ");

        lblUsuari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuari.setText("Usuari:");

        lblConstrasenya.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblConstrasenya.setText("Constrasenya:");

        txtContrasenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenyaActionPerformed(evt);
            }
        });

        btneEnviar.setText("Enviar");
        btneEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneEnviarActionPerformed(evt);
            }
        });

        Font font = lblRecuperaCOntrasenya.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        lblRecuperaCOntrasenya.setFont(font.deriveFont(attributes));
        lblRecuperaCOntrasenya.setForeground(new java.awt.Color(0, 153, 255));
        lblRecuperaCOntrasenya.setText("Recuperar Contrasenya");
        lblRecuperaCOntrasenya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecuperaCOntrasenyaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(lblInici))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRecuperaCOntrasenya)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblConstrasenya)
                                    .addComponent(lblUsuari))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btneEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUsuari, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtContrasenya, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInici)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuari)
                    .addComponent(txtUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConstrasenya)
                    .addComponent(txtContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btneEnviar)
                .addGap(26, 26, 26)
                .addComponent(lblRecuperaCOntrasenya)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblInici1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInici1.setText("IMATGE EQUIP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lblInici1)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInici1)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtContrasenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenyaActionPerformed

    private void btneEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneEnviarActionPerformed
         Usuari usu = null;
    
    if (txtUsuari.getText().isEmpty() || txtContrasenya.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Error. El nom o la contrasenya estan buits", "Error", JOptionPane.ERROR_MESSAGE);
    return;
    } else {
             try {
                 usu = capaOracleJDBC.obtenirUsuari(txtUsuari.getText().trim(), txtContrasenya.getText().trim());
             } catch (GestorBDClubEsportiuException ex) {
                 Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
             }
        if (usu == null) {
            JOptionPane.showMessageDialog(this, "Error. El nom o la contrasenya son incorrectes", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {

            
 
            FinestraLogin finestraLogin = new FinestraLogin(usu,capaOracleJDBC);
            finestraLogin.setVisible(true); 
            this.dispose(); 
        }
    }

    }//GEN-LAST:event_btneEnviarActionPerformed

    private void lblRecuperaCOntrasenyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperaCOntrasenyaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRecuperaCOntrasenyaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
try {
    javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
} catch (UnsupportedLookAndFeelException ex) {
    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex); // Incluye 'ex' para registrar el error
}
 
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

//        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (args.length == 0) {
                    System.out.println("Cal passar el nom de la classe que dona la persistència com a primer argument");
                    System.exit(0);
                }
                nomClassePersistencia = args[0];
                new Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneEnviar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConstrasenya;
    private javax.swing.JLabel lblInici;
    private javax.swing.JLabel lblInici1;
    private javax.swing.JLabel lblRecuperaCOntrasenya;
    private javax.swing.JLabel lblUsuari;
    private javax.swing.JTextField txtContrasenya;
    private javax.swing.JTextField txtUsuari;
    // End of variables declaration//GEN-END:variables
}
